import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const proxima_nova = localFont({
  src: [
    {
      path: 'fonts/Proxima-Nova-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: 'fonts/Proxima-Nova-Semibold.otf',
      weight: '500',
      style: 'semibold',
    },
    {
      path: 'fonts/Proxima-Nova-Bold.otf',
      weight: '600',
      style: 'bold',
    },
    {
      path: 'fonts/Proxima-Nova-Extrabold.otf',
      weight: '800',
      style: 'extrabold',
    },
  ],
})

const interstate_condensed = localFont({
  src: [
    {
      path: 'fonts/interstate-25.ttf',
      weight: '400',
      style: 'normal'
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={proxima_nova.className}>{children}</body>
    </html>
  );
}
